### ISSUE TITLE
Failed to create plugin instance

### ISSUE THREAD

**Issue by master-lingchan** [AlexProgrammerDE/PistonMOTD#123]
I experienced an error during the starting process of server, following info is the console error messages:
Runtime environments:
OS: Ubuntu 18.04.4 x86_64
JVM Startup script and options:
`java -Xms2048M -Xmx3072M -Dlog4j2.formatMsgNoLookups=true -jar forge-1.16.5-36.2.34.jar -nogui`
Minecraft & Forge version: 1.16.5

`[15:01:40] [modloading-worker-1/ERROR] [or.sp.fo.la.pl.PluginModContainer/LOADING]: Failed to create plugin instance. PluginID: pistonmotd, class net.pistonmaster.pistonmotd.sponge.PistonMOTDSponge
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: net/pistonmaster/pistonmotd/shadow/apache/logging/log4j/Logger
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.inject.internal.FailableCache.get(FailableCache.java:54) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:148) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592) ~[?:?] {re:classloading}
        at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:176) ~[?:?] {re:classloading}
        at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:163) ~[?:?] {re:classloading}
        at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49) ~[?:?] {re:classloading}
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:126) ~[?:?] {re:classloading}
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:244) ~[?:?] {re:classloading}
        at org.spongepowered.forge.launch.plugin.PluginModContainer.constructPlugin(PluginModContainer.java:62) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1115] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.ModContainerMixin_Forge,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}
Caused by: java.lang.NoClassDefFoundError: net/pistonmaster/pistonmotd/shadow/apache/logging/log4j/Logger
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3296) ~[?:?] {}
        at java.lang.Class.getDeclaredConstructors(Class.java:2515) ~[?:?] {}
        at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:292) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:117) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:716) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:941) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:843) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:301) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:224) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createParameterInjector(InjectorImpl.java:1035) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.getParametersInjectors(InjectorImpl.java:1022) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:70) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34) ~[?:?] {re:classloading}
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43) ~[?:?] {re:classloading}
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        ... 24 more
Caused by: java.lang.ClassNotFoundException: net.pistonmaster.pistonmotd.shadow.apache.logging.log4j.Logger
        at java.lang.ClassLoader.findClass(ClassLoader.java:719) ~[?:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.1.3.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3296) ~[?:?] {}
        at java.lang.Class.getDeclaredConstructors(Class.java:2515) ~[?:?] {}
        at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:292) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:117) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:716) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:941) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:843) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:301) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:224) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.createParameterInjector(InjectorImpl.java:1035) ~[?:?] {re:classloading}
        at com.google.inject.internal.InjectorImpl.getParametersInjectors(InjectorImpl.java:1022) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:70) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38) ~[?:?] {re:classloading}
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34) ~[?:?] {re:classloading}
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43) ~[?:?] {re:classloading}
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        ... 24 more
        Suppressed: java.lang.ClassNotFoundException
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.1.3.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
                at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
                at java.lang.Class.privateGetDeclaredConstructors(Class.java:3296) ~[?:?] {}
                at java.lang.Class.getDeclaredConstructors(Class.java:2515) ~[?:?] {}
                at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:292) ~[?:?] {re:classloading}
                at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:117) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:716) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:941) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:843) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:301) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:224) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.createParameterInjector(InjectorImpl.java:1035) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.getParametersInjectors(InjectorImpl.java:1022) ~[?:?] {re:classloading}
                at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:70) ~[?:?] {re:classloading}
                at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30) ~[?:?] {re:classloading}
                at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38) ~[?:?] {re:classloading}
                at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34) ~[?:?] {re:classloading}
                at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43) ~[?:?] {re:classloading}
                at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
                at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
                at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
                at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
                at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
                at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
                at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
                at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
                at com.google.inject.internal.FailableCache.get(FailableCache.java:54) ~[?:?] {re:classloading}
                at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49) ~[?:?] {re:classloading}
                at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:148) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592) ~[?:?] {re:classloading}
                at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:176) ~[?:?] {re:classloading}
                at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:163) ~[?:?] {re:classloading}
                at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49) ~[?:?] {re:classloading}
                at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:126) ~[?:?] {re:classloading}
                at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239) ~[?:?] {re:classloading}
                at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:244) ~[?:?] {re:classloading}
                at org.spongepowered.forge.launch.plugin.PluginModContainer.constructPlugin(PluginModContainer.java:62) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1115] {re:classloading}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.ModContainerMixin_Forge,pl:mixin:A}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) [?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}
`
And following file is crash reports:
[crash-2022-05-06_15.01.41-fml.txt](https://github.com/AlexProgrammerDE/PistonMOTD/files/8638300/crash-2022-05-06_15.01.41-fml.txt)

**Comment by yudonglin** [comment]
Same on Ubuntu 22.04, not sure whether this is a linux OS problem. It also seems like it has something to do with the log4j system.

**Comment by AlexProgrammerDE** [comment]
Has been fixed with https://github.com/AlexProgrammerDE/PistonMOTD/commit/e8335a55f03089b4f729191f2f5de1bb0703eb63
Will be released with the next update.
